// profile related interactions
export const ADD_PROFILE_PICTURE = 'ADD_PROFILE_PICTURE';
export const ADD_PROFILE_NAME = 'ADD_PROFILE_NAME';
export const ADD_PROFILE_HOME = 'ADD_PROFILE_HOME';
export const ADD_PROFILE_CURRENT_LOCATION = 'ADD_PROFILE_CURRENT_LOCATION';
export const ADD_PROFILE_BIO = 'ADD_PROFILE_BIO';
export const ADD_PROFILE_INTEREST = 'ADD_PROFILE_INTEREST';
export const REMOVE_PROFILE_INTEREST = 'REMOVE_PROFILE_INTEREST';
export const ADD_PROFILE_SOCIAL_ACCOUNT = 'ADD_PROFILE_SOCIAL_ACCOUNT';

// account related interactions
export const TOGGLE_LIMITED_DEALS = 'TOGGLE_LIMITED_DEALS';
export const TOGGLE_NEWSLETTER_NOTIFICATIONS = 'TOGGLE_NEWSLETTER_NOTIFICATIONS';

// trip update related interactions
export const ADD_TRIP_NAME = 'ADD_TRIP_NAME';
export const ADD_TRIP_DESTINATION = 'ADD_TRIP_DESTINATION';
export const ADD_TRIP_DATE_RANGE = 'ADD_TRIP_DATE_RANGE';
export const ADD_TRIP_BUDGET = 'ADD_TRIP_BUDGET';
export const UPDATE_TRIP_IMAGE_STORE = 'UPDATE_TRIP_IMAGE_STORE';
export const ADD_TRIP_TRAVELLER = 'ADD_TRIP_TRAVELLER';
export const ADD_TODO_LIST = 'ADD_TODO_LIST';
