name: Upload to project branch

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Deploy Backend Dev", "Deploy Frontend Dev"]
    branches: ["project_[0-9]-dev"]
    types:
      - completed
env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  upload-branch:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v5
      - name: Upload to branch
        run: |
          git config --global user.name 'Trek Service"
          git config --global user.email "trekkers.project@gmail.com"
          git checkout $BRANCH_NAME
          git merge --no-edit $BRANCH_NAME-dev
        
      
    
