name: Deploy Backend Dev
on:
  push:
    branches:
      - "project_[0-9]-dev"
jobs:
  deploy:
    name: Deploy Backend Dev
    runs-on: ubuntu-latest
    concurrency: deploy-group    # optional: ensure only one action runs at a time
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Backend
        run: |
         cd backend
         echo "HOSTNAME=trek-dev.wyfx.ca" >> .env
         npm install
         npm run build
  
      - name: Upload to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.WYFX_HOST }}
          username: ${{ secrets.WYFX_USERNAME }}
          password: ${{ secrets.WYFX_PASSWORD }}
          port: ${{ secrets.WYFX_PORT }}
          source: "backend/src/*,backend/package.json,backend/package-lock.json,backend/public/*,backend/bin/*,backend/dist/*,backend/tsconfig.json"
          target: "api"
          overwrite: true
          strip_components: 1

